---
rules:
  preset-japanese: true
  preset-jtf-style:
    3.1.1.全角文字と半角文字の間: false
  prh:
    rulePaths: [./prh.yml]
filters:
  # textlint-filter-rule-allowlist を使う場合は以下の指示に従ってください
  # 1. `npm i textlint-filter-rule-allowlist -D` を実行
  # 2. ./textlintallow.yml の中身を適切に編集
  # 3. 次の 2 行をアンコメント
  # allowlist:
  #   allowlistConfigPaths: [./textlintallow.yml]
  comments: true
