#!/bin/sh
# shellcheck disable=SC1091
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

# .textlintignoreでfoo.mdを無視するように指定していたとしても、`textlint foo.md` を実行するとfoo.md
# に対してlintが実行されてしまう。そこで、textlintについてはlint-staged内ではなく個別に実行する
npm run lint:text
