---
name: reviewdog
on: pull_request
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: . .?*/**/*.{md,markdown}
      - name: textlint
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: . .?*/**
      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          pattern: |
            *.sh
            commit-msg
            pre-commit
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
